[project]
name = "xyplug-on-holiday"
version = "1.0.3"
description = "xyOps plugin to skip or execute jobs on public holidays"
requires-python = ">=3.9"
dependencies = [
    "requests"
]

[project.scripts]
xyplug-on-holiday = "on_holiday.main:main"

[tool.setuptools]
packages = ["on_holiday"]
